
version: '3.8'

services:
  ai-code-translator:
    build: .
    container_name: ai_code_translator
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment: